CREATE TABLE "agent_events" (
	"session_id" text NOT NULL,
	"stream_ms" bigint GENERATED BY DEFAULT AS IDENTITY (sequence name "agent_events_stream_ms_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1800000000000000 CACHE 1),
	"stream_seq" bigint DEFAULT 0 NOT NULL,
	"event" jsonb NOT NULL,
	CONSTRAINT "agent_events_session_id_stream_ms_stream_seq_pk" PRIMARY KEY("session_id","stream_ms","stream_seq")
);
--> statement-breakpoint
ALTER TABLE "agent_sessions" ADD COLUMN "events_backfilled_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "workspaces" ADD COLUMN "deleted_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "workspaces" ADD COLUMN "purge_started_at" timestamp with time zone;--> statement-breakpoint
ALTER TABLE "agent_events" ADD CONSTRAINT "agent_events_session_id_agent_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."agent_sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "workspaces_deleted_at_idx" ON "workspaces" USING btree ("deleted_at");